services:
  mya:
    extends:
      file: deps.yaml
      service: mya

  softioc:
    extends:
      file: deps.yaml
      service: softioc

  myquery:
    extends:
      file: deps.yaml
      service: myquery

  epics2web:
    extends:
      file: deps.yaml
      service: epics2web

  wave:
    hostname: wave
    container_name: wave
    ports:
      - 8080:8080
    environment:
      EPICS_2_WEB_HOST: localhost:8086
      MYQUERY_HOST: localhost:8085
      MYQUERY_DEFAULT_DEPLOYMENT: docker
